### ISSUE TITLE
owners field is required and add support for YSQL

### ISSUE THREAD

**Issue by jaykumarthaker** [YugaByte/terraform-aws-yugabyte#3]
Um I am still experimenting with Yugabyte. My sole purpose is to install Yugabyte on AWS and later if possible connect it through PgAdmin.
Terraform was asking for owners field hence specified in
./terraform/modules/0d32.../main.tf as:
```
data "aws_ami" "yugabyte_ami" {
 most_recent = true  filter {
   name = "name"    values = [
     "amzn-ami-hvm-*-x86_64-gp2",
   ]
 }  filter {
   name = "owner-alias"    values = [
     "amazon",
   ]
 } 
owners=["amazon","aws-marketplace"]
}
```

So, um if possible, I think we should fix this..
and the other issue was that, I cannot connect to port 5433! (https://docs.yugabyte.com/latest/quick-start/explore-ysql/#1-load-data)
I verified through **netstat -tupln**
and there nothing listening on 5433 port.. (hoping this is due to lack of YSQL support)

**Comment by ajcaldera1** [comment]
Fixed with commit  e3fdf04
